### ISSUE TITLE
Mapping von Portalen

### ISSUE THREAD

**Issue by s-hell** [blabber/tintin-morgengrauen#1]
Hi,

ich bin begeistert von diesem Repo und spiele da schon eine ganze Zeit mit rum. Es gibt aber noch eine Sache, die ich nicht wirklich verstehe oder wo ich vermutlich einen Denkfehler habe:

Wie kartografiert man eigentlich z.B. ein Portal.

Laut deiner Readme wäre das ja mit

#map dig o
#map exit o command {betrete portal}

Das macht aber so bei einem Portal ja eigentlich keinen Sinn. Wie müsste man das richtig machen? Hast du dafür schon eine Lösung?

**Comment by blabber** [comment]
Hi. Ich wollte nur kurz von mir hören lassen, damit du nicht denkst du würdest uns Leere kommunizieren. Ich hab nur gerade noch Urlaub. Ab Montag habe ich wieder eine richtige Tastatur vor mir und kann dann auch sinnvoll antworten ;)

**Comment by s-hell** [comment]
Dann auf jeden Fall erst mal einen schönen Urlaub.

Ich bastel gerade noch ein wenig mit exitflags und hide rum. Aber so richtig schön ist das glaube ich auch noch nicht.

**Comment by blabber** [comment]
Mir ist nicht ganz klar, was du unter einem "Portal" verstehst. Ich kann mir darunter zwei Dinge vorstellen:

1. ein Portal durch das du ein Gebäude betrittst
2. ein Portal das dich tatsächlich, unabhängig von der Geografie, irgendwohin teleportiert

### Mapping von Portalen durch die du ein Gebäude betrittst

Hier nutze ich ein Mischmasch aus drei Varianten.

#### Variante 1: Sichtbarer Ausgang mit Exitflag "hide"

Das ist die Variante die ich am häufigsten verwende. Wenn es irgendwo ein Gebäude gibt, das betreten werden kann und noch eine der regulären Himmelsrichtungen frei ist, dann lege ich einen Ausgang in eine ungenutzte Richtung an und setze das "hidden" Exitflag. In dem Screenshot wäre das der Ausgang nach "Westen".

![Variante 1](https://user-images.githubusercontent.com/1199257/143846789-5cc06a97-a688-4d24-80b3-53283b698928.png)

#### Variante 2: Sichtbarer Ausgang mit Exitflag "hide" und einem als Label missbrauchten Roomsymbol

Das ist die Variante die ich manchmal verwende, wenn mir der Bereich der betreten wird besonders interessant erscheint. Im Prinzip lege ich dann auch einen Raum in eine Himmelsrichtung an die noch frei ist, allerdings setze ich dann nicht das Exitflag sondern schreibe ein Label in das Roomsymbol (bei Verwendung der Unicodedarstellung passen da 5 Zeichen rein, bei ASCII 6 Zeichen). Wenn es aus dem Eingangsraum weiter in andere Räume geht, dann verstecke ich die entsprechenden Ausgänge mittels Exitflags. 

![Variante 2](https://user-images.githubusercontent.com/1199257/143848378-59036a81-b819-4cd4-9695-2fb006c6195f.png)

#### Variante 3: Ausgänge die nicht in der Karte dargestellt werden.

Das ist die Variante, die ich bisher nur einmal verwendet habe. Du kannst beliebige Ausgänge anlegen und bist nicht auf die auf der Karte darstellbaren Varianten beschränkt. In dem Screenshot siehst du, dass alle Himmelsrichtungen bereits durch reguläre Ausgänge belegt sind. Entsprechend habe ich einen Ausgang namens "betrete turm" angelegt um den Turm zu betreten.

![Variante 3](https://user-images.githubusercontent.com/1199257/143850848-b2228ee9-44c9-4414-bb92-092782c18866.png)

### Mapping von Portalen die dich irgendwohin teleportieren

Ich bin bisher noch nicht in die Situation gekommen sowas kartografieren zu müssen und kann daher nicht aus Erfahrung sprechen. Ich glaube ich würde hier einen Ausgang der nicht auf der Karte dargestellt wird verwenden (Variante 3 von oben). Falls der Ort zu dem teleportiert wird bereits kartografiert ist, würde ich den Telport vermutlich mittels `#map link {betrete portal} <...>` erstellen.

**Comment by s-hell** [comment]
Ich nehme B

Aber der Rest klang auch interessant. Werde ich mir noch mal anschauen. Danke für die Hilfe. Vielleicht sieht man sich ja mal in Game.

**Comment by blabber** [comment]
Freut mich, wenn ich dir helfen konnte. Das Problem ist halt, dass es beim Mapping so viele verschiedene Möglichkeiten gibt und jeder seinen eigenen Weg finden muss. Im Endeffekt musst du ja mit der Karte klar kommen.

> Vielleicht sieht man sich ja mal in Game.

Hehe. Aktuell stehe ich idle im Hobbitwald rum, weil ich statt zu spielen gerade dabei bin diesen Spaghetticode aufzuräumen :)

**Comment by Kebap** [comment]
Die Portale bekommt man noch nicht anfangs, aber später kannst du dich mal in der Fraternitas durchfragen.. 😉
